# _config.yml for GitHub Pages (static site)
# Prevent Jekyll from processing files
exclude:
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - .github
  - .vscode
  - .idea
  - .replit
  - replit.nix
  - .config

# Set the baseurl to match your repository name
baseurl: "/Portfolio"

# GitHub Pages theme and site info
theme: jekyll-theme-minimal
title: Akshar Kakumani's Portfolio
description: Bookmark this to keep an eye on my project updates! 